package jp.dodododo.dao.sql.no_update;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import jp.dodododo.dao.wrapper.ConnectionWrapper;

public class NUConnection extends ConnectionWrapper {

	public NUConnection(Connection connection) {
		super(connection);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return new NUPreparedStatement(super.prepareStatement(sql), sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return prepareStatement(sql);
	}

	@Override
	public Statement createStatement() throws SQLException {
		return prepareStatement("");
	}

	@Override
	public Statement createStatement(int arg0, int arg1) throws SQLException {
		return prepareStatement("");
	}

	@Override
	public Statement createStatement(int arg0, int arg1, int arg2) throws SQLException {
		return prepareStatement("");
	}

}
